=== Inexorable-Fate/mpc_projects/projects.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Projects",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "content": {
      "type": "string"
    },
    "info": {
      "type": ["string", "null"]
    },
    "website": {
      "type": ["string", "null"]
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "created": {
      "type": "string"
    },
    "updated": {
      "type": "string"
    },
    "version": {
      "type": "number"
    },
    "code": {
      "type": "string"
    },
    "cards": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "count": {
            "type": "number"
          },
          "front": {
            "type": "object",
            "properties": {
              "Name": {
                "type": "string"
              },
              "ID": {
                "type": "string"
              },
              "SourceID": {
                "type": "string"
              },
              "Exp": {
                "type": "string"
              },
              "Width": {
                "type": "number"
              },
              "Height": {
                "type": "number"
              }
            },
            "required": [
              "Name",
              "ID",
              "SourceID",
              "Exp",
              "Width",
              "Height"
            ]
          },
          "back": {
            "type": "object",
            "properties": {
              "Name": {
                "type": "string"
              },
              "ID": {
                "type": "string"
              },
              "SourceID": {
                "type": "string"
              },
              "Exp": {
                "type": "string"
              },
              "Width": {
                "type": "number"
              },
              "Height": {
                "type": "number"
              }
            },
            "required": [
              "Name",
              "ID",
              "SourceID",
              "Exp",
              "Width",
              "Height"
            ]
          }
        },
        "required": [
          "count",
          "front",
          "back"
        ]
      }
    },
    "hash": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "name",
    "description",
    "content",
    "info",
    "website",
    "authors",
    "tags",
    "created",
    "updated",
    "version",
    "code",
    "cards",
    "hash"
  ]
}

=== Inexorable-Fate/mpc_projects/public/projects/Parallel 06 Ashcan Pete (3).json
{
  "id": "58539D4AE7D79DA95857DEADE1E2448E4B4963FD356165545EA19997855DE4429F123D762C4E8173",
  "name": "Parallel 6: Ashcan Pete",
  "description": "",
  "content": "",
  "info": null,
  "website": null,
  "authors": [
    "Fantasy Flight Games"
  ],
  "tags": [
    "Investigator",
    "Parallel"
  ],
  "created": "2023-08-08T04:45:26.682Z",
  "updated": "2023-08-08T04:45:28.879Z",
  "version": 1,
  "code": "C380050185D1C1AF",
  "cards": [
    {
      "count": 1,
      "front": {
        "Name": "046 Parallel Ashcan Pete-1.png",
        "ID": "576351A416C2E9DC5E8B3635955F9F1A",
        "SourceID": "2F25A4D36E867E76D7007DBB50E0AB8A229346D7",
        "Exp": "png",
        "Width": 822,
        "Height": 1122
      },
      "back": {
        "Name": "046 Parallel Ashcan Pete-2.png",
        "ID": "0F05373B21B29BE006BF5B2F3F246A5E",
        "SourceID": "B8A9C9E658FC309E09102527DCBA0B11481B56B4",
        "Exp": "png",
        "Width": 822,
        "Height": 1122
      }
    },
    {
      "count": 1,
      "front": {
        "Name": "047 Pete's Guitar-1.png",
        "ID": "751DE1D55550F78874AFE0108FF5C045",
        "SourceID": "0813AEC296F7320DBBE78EFB61D167673676A083",
        "Exp": "png",
        "Width": 822,
        "Height": 1122
      },
      "back": {
        "Name": "_playerback.png",
        "ID": "F2C892495D430CF932D00FCC1CD986B8",
        "SourceID": "537898184A74156EB358A1B62F6812262361519E",
        "Exp": "png",
        "Width": 822,
        "Height": 1122
      }
    },
    {
      "count": 1,
      "front": {
        "Name": "048 Hard Times-1.png",
        "ID": "47CC3779F6D3B65581930809C8B7B5D3",
        "SourceID": "AED9617CEA45B43B9964C34C90628C714CD56A7C",
        "Exp": "png",
        "Width": 822,
        "Height": 1122
      },
      "back": {
        "Name": "_playerback.png",
        "ID": "F2C892495D430CF932D00FCC1CD986B8",
        "SourceID": "537898184A74156EB358A1B62F6812262361519E",
        "Exp": "png",
        "Width": 822,
        "Height": 1122
      }
    }
  ],
  "hash": "722c049098852f474985576fe597263d2ab6396dd06a05da2c20f9c7aa6425f6"
}
